# -*- coding: utf-8 -*-
# OPENCLASSROOMS-COURSES-EXPLORER 
# Copyright (c) 2021, Tristan Vanrullen - all rights reserved.
# Note there is a licence for the code and another for the contents generated by the application
# see licence.txt for more details 

from pathlib import Path

import numpy as np
import pandas as pd
import timeit 
import time
import math
import random

import matplotlib.pyplot as plt
# %matplotlib inline
# %matplotlib notebook

from matplotlib_venn import venn2
from matplotlib_venn import venn3

from matplotlib.gridspec import GridSpec


# Handle date time conversions between pandas and matplotlib
from pandas.plotting import register_matplotlib_converters
register_matplotlib_converters()

import seaborn as sns

from IPython.display import display, clear_output, Image, HTML,  IFrame
#Pour une présentation interactive avec voila
# For IPywidgets to work properly on Jupyter Lab:
#(if necessary install nodejs first) conda 
#jupyter labextension install @jupyter-widgets/jupyterlab-manager

from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets

import html
import json

# using the requests library to scap a website mostly populated by Javascript processes & Ajax flows is impossible
import requests
# so Selenium seems to be the only option to get this scrap work done!
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as ec
from selenium.webdriver.common.action_chains import ActionChains
# Please store the Firefox driver from https://github.com/mozilla/geckodriver/releases in the /driver folder
from selenium.webdriver import Firefox, FirefoxOptions

from datetime import date, datetime

#graph and network visualization
from pyvis.network import Network
import networkx as nx

#quick setup
pd.set_option("max_columns", None) # show all cols
#pd.set_option("max_rows", None) # show all rows
pd.set_option('max_colwidth', 80) # show full width of showing cols
pd.set_option("expand_frame_repr", False) # print cols side by side as it's supposed to be

plt.rcParams['figure.dpi'] = 100
plt.rcParams['figure.figsize'] = [6, 2]
plt.style.use('seaborn')
sns.set(style = 'whitegrid') 
font1 = {'family':'sans-serif','color':'blue','size':15}
font2 = {'family':'sans-serif','color':'darkred','size':12}


# ----------------------------------------------------------------------------
# IMPORTANT PATHS AND RESOURCES LINKS SETUP

DatasetsFolder = r"data/"
ImgFolder = r"img/"
VizFolder = r"viz/"
VoilaVizFolder = r"viz/"
# in some environments, it can be a solution to use the original template, because it looks for vis-network.min.js in some internet location
# VizTemplate= r"viz/pyvis_original_template.html" 
VizTemplate= r"viz/vis_template.html"

FirefoxWebdriverPath = r"F:\AIDEV\OCCoursesExplorer\driver\geckodriver.exe" # the path to the webdriver must be absolute

OCGraphsIconsFolderURL = "https://raw.githubusercontent.com/TristanV/OCCoursesExplorer/main/img/" # Icons must be stored somewhere on the web. PyVis won't accept local drives paths
OCGraphsIconsFolderLocal="img/"

OCGraphsIconsURL = {
        "OpenClassrooms"    : OCGraphsIconsFolderURL+"openclassrooms_icon.webp",
        "fr"                : OCGraphsIconsFolderURL+"fr.png",
        "en"                : OCGraphsIconsFolderURL+"uk.png",
        "es"                : OCGraphsIconsFolderURL+"es.png",        
        "topic"             : OCGraphsIconsFolderURL+"topic.png",
        "path"              : OCGraphsIconsFolderURL+"path.png",
        "path_1"            : OCGraphsIconsFolderURL+"path_1.png",
        "path_2"            : OCGraphsIconsFolderURL+"path_2.png",
        "path_3"            : OCGraphsIconsFolderURL+"path_3.png",
        "path_4"            : OCGraphsIconsFolderURL+"path_4.png",
        "path_5"            : OCGraphsIconsFolderURL+"path_5.png",
        "project"           : OCGraphsIconsFolderURL+"project.png",
        "project_todo"           : OCGraphsIconsFolderURL+"project_todo.png",
        "project_in_progress"           : OCGraphsIconsFolderURL+"project_in_progress.png",
        "project_done"           : OCGraphsIconsFolderURL+"project_done.png",
        "project_link"      : OCGraphsIconsFolderURL+"multilink.png",
        "project_jury"      : OCGraphsIconsFolderURL+"jury.png",
        "project_success"   : OCGraphsIconsFolderURL+"project_success.png",
        "course"            : OCGraphsIconsFolderURL+"course.png",
        "course_todo"            : OCGraphsIconsFolderURL+"course_todo.png",
        "course_in_progress"            : OCGraphsIconsFolderURL+"course_in_progress.png",
        "course_done"            : OCGraphsIconsFolderURL+"course_done.png",
        "course_link"       : OCGraphsIconsFolderURL+"link.png",
        "part"              : OCGraphsIconsFolderURL+"part.png",
        "chapter"           : OCGraphsIconsFolderURL+"chapter.png",
        "skill"             : OCGraphsIconsFolderURL+"bright_star.png",
        "course_success"    : OCGraphsIconsFolderURL+"certification.png"  
    } 


OCGraphsIconsLocal = {
        "OpenClassrooms"    : OCGraphsIconsFolderLocal+"openclassrooms_icon.webp",
        "fr"                : OCGraphsIconsFolderLocal+"fr.png",
        "en"                : OCGraphsIconsFolderLocal+"uk.png",
        "es"                : OCGraphsIconsFolderLocal+"es.png",        
        "topic"             : OCGraphsIconsFolderLocal+"topic.png",
        "path"              : OCGraphsIconsFolderLocal+"path.png",
        "path_1"            : OCGraphsIconsFolderLocal+"path_1.png",
        "path_2"            : OCGraphsIconsFolderLocal+"path_2.png",
        "path_3"            : OCGraphsIconsFolderLocal+"path_3.png",
        "path_4"            : OCGraphsIconsFolderLocal+"path_4.png",
        "path_5"            : OCGraphsIconsFolderLocal+"path_5.png",
        "project"           : OCGraphsIconsFolderLocal+"project.png",
        "project_todo"      : OCGraphsIconsFolderLocal+"project_todo.png",
        "project_in_progress": OCGraphsIconsFolderLocal+"project_in_progress.png",
        "project_done"      : OCGraphsIconsFolderLocal+"project_done.png",
        "project_link"      : OCGraphsIconsFolderLocal+"multilink.png",
        "project_jury"      : OCGraphsIconsFolderLocal+"jury.png",
        "project_success"   : OCGraphsIconsFolderLocal+"project_success.png",
        "course"            : OCGraphsIconsFolderLocal+"course.png",
        "course_todo"       : OCGraphsIconsFolderLocal+"course_todo.png",
        "course_in_progress": OCGraphsIconsFolderLocal+"course_in_progress.png",
        "course_done"       : OCGraphsIconsFolderLocal+"course_done.png",
        "course_link"       : OCGraphsIconsFolderLocal+"link.png",
        "part"              : OCGraphsIconsFolderLocal+"part.png",
        "chapter"           : OCGraphsIconsFolderLocal+"chapter.png",
        "skill"             : OCGraphsIconsFolderLocal+"bright_star.png",
        "course_success"    : OCGraphsIconsFolderLocal+"certification.png"  
    } 
 
# OC Theme for graphs     
# OCGraphsBackgroundColor = "#d5d0f5" # some OC palette background color
OCGraphsBackgroundColor = "#FFF" # some OC palette background color
OCGraphsTextColor = "#141414"
